### ISSUE TITLE
How to get the offsets

### ISSUE THREAD

**Issue by Madhu2244** [tntd2k2/LeagueOldDump#1]
Hello, I tried to download as ZIP to get the offsets, but it is not able to open. Can kindly assist me in how to use this repo?

**Comment by tntd2k2** [comment]
Open it with any disassembler like IDA, Gidra, etc and analyse it.

**Comment by tntd2k2** [comment]
You can open it with any disassembler like IDA, Gidra, etc and analyse it.
All file are named with format GameVersion_BaseAddress.exe
```
Example
13.23.544.5515_7FF6C9490000.exe
```
See [All in One Beginner Tutorial](https://www.unknowncheats.me/forum/league-of-legends/567734-beginner-tutorial.html)
This thread will show u some basic step to work with IDA (xref string, calc offsets, etc)
If you want to update ur offset, just search for immediate value or jump to address and sig it using SigMaker.

**Comment by Madhu2244** [comment]
Thank you for your help, this is very useful.
